name: Ctrl+Alt+Enter
favicon: null
layout_spectrum: 0.6478
typography_spectrum: 0.19321614946238697
title: "Service Informatique Individualisé de la Côte d'Émeraude"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70137033-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.17911111656576395
  lightness: 0.5397564901504666
  saturation: 0.7587336979340762
  rhythmicContrast: 0.28921311907470226
purpose: []
